// Define the experimental constants for the color sensor
#define COLOR_RED_R_EBAY 197.57
#define COLOR_RED_G_EBAY 42.86
#define COLOR_RED_B_EBAY 40.43
#define COLOR_RED_MAX_DISTANCE_EBAY 30.7 // Original is 10.7

#define COLOR_GREEN_R_EBAY 106.41
#define COLOR_GREEN_G_EBAY 106.35
#define COLOR_GREEN_B_EBAY 50.35
#define COLOR_GREEN_MAX_DISTANCE_EBAY 21.4

#define COLOR_BLUE_R_EBAY 63.14
#define COLOR_BLUE_G_EBAY 98.29
#define COLOR_BLUE_B_EBAY 109
#define COLOR_BLUE_MAX_DISTANCE_EBAY 7.8